### ISSUE TITLE
Invalid Slot Error

### ISSUE THREAD

**Issue by Blackhalo714** [ThornyFFXI/Stylist#4]
Trying to get help.  I do not know if I am entering wrong command input on my end or a issue.   Stylist loads,  Blink options work. Try to add any model and get invalid [slot} error.  Thank you.

**Comment by ThornyFFXI** [comment]
Git issues are for actual bug reports and feature requests.  You haven't provided enough data to give any indication this is an actual bug, and didn't even include the command you're using.  An example model filter would be:
`/sl addmodel body "Brigandine" "Scorpion Harness"`
which would convert all brigandines to scorpion harnesses for everyone.  If this does not work for you, then it may be a bug.  Otherwise, it's probably a user error.

**Comment by Blackhalo714** [comment]
Hello, sorry for the lack of other information.  I was trying to get help on discord.

  I am trying to do this command from the readme.

/sl addc [Required: Character Name] [Required: Equipment Slot] [Required: Model]

When I type
/sl chaosdream body 13757
Says invalid slot specified [body]

________________________________

**Comment by ThornyFFXI** [comment]
This is still a user error, please do not reply again here or on github.  That dings my personal phone for something that quite frankly is not important to me.  Questions like this can be answered by many people on the Ashita discord.  Github issues are for bugs and suspected bugs, not user assistance.

You seem to have misread the command, you need to include the 'addc'.

`/sl addc Chaosdream body 13757`
